# Copyright 2019 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 

steps:

# Clone the source code
- name: 'gcr.io/cloud-builders/git'
  args: 
      [
       'clone', 
       'https://github.com/prakhag1/pubsub-proxy-grpc'
      ]

# Maven package
- name: 'gcr.io/cloud-builders/mvn'
  args: 
      [
       'clean', 
       'compile', 
       'assembly:assembly', 
       'package'
      ]
  dir: 'pubsub-proxy-grpc'

# Build application image
- name: 'gcr.io/cloud-builders/docker'
  args: 
      [
       "build", 
       "--tag=gcr.io/$PROJECT_ID/pubsub-proxy-grpc", 
       "."
      ]
  dir: 'pubsub-proxy-grpc'

images: 
- 'gcr.io/$PROJECT_ID/pubsub-proxy-grpc'
