steps:

# Clone the source code
- name: 'gcr.io/cloud-builders/git'
  args: 
      [
       'clone', 
       'https://github.com/prakhag1/pubsub-proxy-grpc'
      ]

# Create custom builder for protoc
- name: 'gcr.io/cloud-builders/docker'
  args:
      [
        'build',
        '-f',
        'Dockerfile.protoc',
        '--tag',
        'gcr.io/$PROJECT_ID/protoc',
        '--cache-from',
        'gcr.io/$PROJECT_ID/protoc',
        '.'
      ]
  dir: 'pubsub-proxy-grpc'

# Get googleapis required to build descriptor pb
- name: 'gcr.io/cloud-builders/git'
  args:
      [
        'clone',
        'https://github.com/googleapis/googleapis'
      ]
  dir: 'pubsub-proxy-grpc'

# Generate api descriptor manifest and store the artifact in GCS 
- name: 'gcr.io/$PROJECT_ID/protoc'
  args:
      [
        '-I.',
        '--include_imports',
        '--include_source_info',
        '--proto_path=./googleapis/',
        '--descriptor_set_out=api_descriptor.pb',
        'descriptors/proxy.proto'
      ]
  dir: 'pubsub-proxy-grpc'
artifacts:
  objects:
    location: "gs://${_ARTIFACT}/"
    paths: ['api_descriptor.pb']

substitutions:
    _ARTIFACT: [ARTIFACT]
