type: google.api.Service
config_version: 3

# Name of the service configuration.
name: pubsub-proxy.endpoints.[PROJECT_ID].cloud.goog

title: Pubsub gRPC API
apis:
- name: org.examples.grpc.pubsub.generated.PubsubProxyService

usage:
  rules:
  - selector: org.examples.grpc.pubsub.PubsubProxyService.GetHealth
    allow_unregistered_calls: true
  - selector: org.examples.grpc.pubsub.PubsubProxyService.Publish
    allow_unregistered_calls: true
